AWSTemplateFormatVersion: 2010-09-09
Description: >-
  aws-lambda-node

Transform:
- AWS::Serverless-2016-10-31

Resources:
  listFormulasFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/list-formulas.listFormulasHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A function to list items from a DynamoDB table and paginate the results.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FormulasTable
      Environment:
        Variables:
          FORMULAS_TABLE: FormulasTable
          ZFAB_INDEX: zfab-index
          REDIRECT_URL_INDEX: redirectUrl-index
      Events:
        Api:
          Type: Api
          Properties:
            Path: formulas/list
            Method: GET
  getFormulaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-formula.getFormulaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A function to find an item in a DynamoDB table from its primary key.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FormulasTable
      Environment:
        Variables:
          FORMULAS_TABLE: FormulasTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: formulas/{formulaKey}
            Method: GET
  updateFormulaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/update-formula.updateFormulaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A function to update an item in a DynamoDB table from its primary key.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FormulasTable
      Environment:
        Variables:
          FORMULAS_TABLE: FormulasTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: formulas/{formulaKey}
            Method: PATCH
  FormulasTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
